name: Refactor Template
description: Refactor 시 작성 부탁드립니다 :)
title: "[Refactor]: "
labels: [""]

body:
  - type: textarea
    id: issue-contents
    attributes:
      label: 📑Refactor 설명
      description: 작업할 Refactor 에 대한 설명을 작성
      placeholder: - 불필요한 주석 제거
- 하나의 함수 최대한 하나의 역할만 하도록 수정
- 함수 및 변수 명 직관적인 이름으로 변경
- 조건문에 있는 내용 함수로 빼서 더 직관적으로 읽을 수 있게 변경
- 코드가 위에서 아래로 술술 읽히도록 함수 위치 조정
- 반복되는 코드 최대한 재사용할 수 있도록 변경

    validations:
      required: true
  - type: textarea
    id: task-list
    attributes:
      label: 🔲작업 목록
      description: 작업할 목록을 체크박스로 표시
      placeholder: 
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: ✔️참고 사항(Optional)
      description: 참고해야할 내용을 작성
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: estimated-time-to-complete
    attributes:
      label: 🕜예상 소요 시간(Optional)
      description: 작업 예상 소요 시간을 작성
      placeholder: ex) 2일 or 5월 3일 까지
    validations:
      required: false
